package GUI;

public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonBienvenida = new MyContainers.BotonCustomWelcome();
        bienvenida1 = new javax.swing.JLabel();
        bienvenida2 = new javax.swing.JLabel();
        logoUsil = new javax.swing.JLabel();
        background1 = new MyContainers.Background();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBienvenida.setText("LET'S START");
        botonBienvenida.setFocusPainted(false);
        botonBienvenida.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        botonBienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBienvenidaActionPerformed(evt);
            }
        });
        jPanel1.add(botonBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 410, 250, 50));

        bienvenida1.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida1.setText("¡Bienvenido a la app móvil de USIL, tu portal");
        jPanel1.add(bienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 270, 260, 20));

        bienvenida2.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida2.setText(" personal para una experiencia educativa sin límites!");
        jPanel1.add(bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 286, -1, -1));

        logoUsil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usilLogo190x190.png"))); // NOI18N
        jPanel1.add(logoUsil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBienvenidaActionPerformed
        Login ventanaLogin = new Login();
        ventanaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonBienvenidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyContainers.Background background1;
    private javax.swing.JLabel bienvenida1;
    private javax.swing.JLabel bienvenida2;
    private MyContainers.BotonCustomWelcome botonBienvenida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoUsil;
    // End of variables declaration//GEN-END:variables
}
