package GUI;

public class Contactos extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Contactos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bienvenida2 = new javax.swing.JLabel();
        panelRound1 = new MyContainers.PanelRound();
        panelRound2 = new MyContainers.PanelRound();
        n7 = new javax.swing.JLabel();
        As1 = new javax.swing.JLabel();
        panelRound3 = new MyContainers.PanelRound();
        As2 = new javax.swing.JLabel();
        n8 = new javax.swing.JLabel();
        panelRound4 = new MyContainers.PanelRound();
        As4 = new javax.swing.JLabel();
        n10 = new javax.swing.JLabel();
        n12 = new javax.swing.JLabel();
        panelRound5 = new MyContainers.PanelRound();
        As5 = new javax.swing.JLabel();
        n11 = new javax.swing.JLabel();
        panelRound6 = new MyContainers.PanelRound();
        As = new javax.swing.JLabel();
        PaSe = new javax.swing.JLabel();
        n6 = new javax.swing.JLabel();
        panelRound7 = new MyContainers.PanelRound();
        As3 = new javax.swing.JLabel();
        n13 = new javax.swing.JLabel();
        n9 = new javax.swing.JLabel();
        n14 = new javax.swing.JLabel();
        n15 = new javax.swing.JLabel();
        n16 = new javax.swing.JLabel();
        n17 = new javax.swing.JLabel();
        facebook1 = new javax.swing.JLabel();
        facebook2 = new javax.swing.JLabel();
        facebook3 = new javax.swing.JLabel();
        facebook4 = new javax.swing.JLabel();
        facebook5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        n18 = new javax.swing.JLabel();
        n19 = new javax.swing.JLabel();
        background1 = new MyContainers.Background();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenida2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bienvenida2.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida2.setText("CONTACTO");
        jPanel1.add(bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundTopLeft(80);
        panelRound1.setRoundTopRight(80);

        panelRound2.setBackground(new java.awt.Color(204, 204, 204));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        n7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n7.setForeground(new java.awt.Color(41, 61, 109));
        n7.setText("317-1090");
        n7.setAlignmentX(0.5F);

        As1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As1.setForeground(new java.awt.Color(41, 61, 109));
        As1.setText("Emergencias USIL");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(n7))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(As1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(As1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n7)
                .addGap(16, 16, 16))
        );

        panelRound3.setBackground(new java.awt.Color(204, 204, 204));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        As2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As2.setForeground(new java.awt.Color(41, 61, 109));
        As2.setText("Soporte aula virtual");

        n8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n8.setForeground(new java.awt.Color(41, 61, 109));
        n8.setText("317-1010 opción 1");
        n8.setAlignmentX(0.5F);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(As2)
                    .addComponent(n8))
                .addGap(28, 28, 28))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(As2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n8)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        As4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As4.setForeground(new java.awt.Color(41, 61, 109));
        As4.setText("Soporte INFOSIL");

        n10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n10.setForeground(new java.awt.Color(41, 61, 109));
        n10.setText("helpdesk@usil.edu.pe");
        n10.setAlignmentX(0.5F);

        n12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n12.setForeground(new java.awt.Color(41, 61, 109));
        n12.setText("317-1010 opción 2");
        n12.setAlignmentX(0.5F);

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(As4)
                .addGap(41, 41, 41))
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(n12)
                    .addComponent(n10))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(As4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(n10)
                .addContainerGap())
        );

        panelRound5.setBackground(new java.awt.Color(204, 204, 204));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);

        As5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As5.setForeground(new java.awt.Color(41, 61, 109));
        As5.setText("Central telefónica USIL");

        n11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n11.setForeground(new java.awt.Color(41, 61, 109));
        n11.setText("317-1000");
        n11.setAlignmentX(0.5F);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(As5))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(n11)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(As5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n11)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelRound6.setBackground(new java.awt.Color(204, 204, 204));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        As.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As.setForeground(new java.awt.Color(41, 61, 109));
        As.setText("Aseguradora");

        PaSe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PaSe.setForeground(new java.awt.Color(41, 61, 109));
        PaSe.setText("Pacifico Seguros");

        n6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n6.setForeground(new java.awt.Color(41, 61, 109));
        n6.setText("415-1515");
        n6.setAlignmentX(0.5F);

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(As)
                .addGap(50, 50, 50))
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(n6))
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(PaSe)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(As)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaSe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        panelRound7.setBackground(new java.awt.Color(204, 204, 204));
        panelRound7.setRoundBottomLeft(20);
        panelRound7.setRoundBottomRight(20);
        panelRound7.setRoundTopLeft(20);
        panelRound7.setRoundTopRight(20);

        As3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As3.setForeground(new java.awt.Color(41, 61, 109));
        As3.setText("Asesor de servicios");

        n13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n13.setForeground(new java.awt.Color(41, 61, 109));
        n13.setText("atencionalumno@usil.edu.pe");
        n13.setAlignmentX(0.5F);

        n9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n9.setForeground(new java.awt.Color(41, 61, 109));
        n9.setText("317-1010 opción 3");
        n9.setAlignmentX(0.5F);

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(n9)
                            .addComponent(As3)))
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(n13)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(As3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n13)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        n14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n14.setForeground(new java.awt.Color(41, 61, 109));
        n14.setText("www.facebook.com/usil.peru");
        n14.setAlignmentX(0.5F);

        n15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n15.setForeground(new java.awt.Color(41, 61, 109));
        n15.setText("www.twitter.com/_USIL");
        n15.setAlignmentX(0.5F);

        n16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n16.setForeground(new java.awt.Color(41, 61, 109));
        n16.setText("www.instagram.com/usil/");
        n16.setAlignmentX(0.5F);

        n17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n17.setForeground(new java.awt.Color(41, 61, 109));
        n17.setText("www.youtube.com/user/usilpe");
        n17.setAlignmentX(0.5F);

        facebook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebookRedi.png"))); // NOI18N
        facebook1.setText("jLabel2");

        facebook2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/instagramRedi2.png"))); // NOI18N
        facebook2.setText("jLabel2");

        facebook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/youtubeRedi.png"))); // NOI18N
        facebook3.setText("jLabel2");

        facebook4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tiktokRedi2.png"))); // NOI18N
        facebook4.setText("jLabel2");

        facebook5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whatsappRedi2.png"))); // NOI18N
        facebook5.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TwitterXRedi3.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        n18.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n18.setForeground(new java.awt.Color(41, 61, 109));
        n18.setText("www.tiktok.com/@usil.edu");
        n18.setAlignmentX(0.5F);

        n19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n19.setForeground(new java.awt.Color(41, 61, 109));
        n19.setText("981-313-100");
        n19.setAlignmentX(0.5F);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(facebook1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(facebook2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n14)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(n15)
                                .addComponent(n16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(facebook5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facebook3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facebook4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n18)
                            .addComponent(n17)
                            .addComponent(n19))
                        .addGap(25, 25, 25))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facebook1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n14)
                    .addComponent(n17)
                    .addComponent(facebook3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n15)
                        .addComponent(jLabel1)
                        .addComponent(n18))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(facebook4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n16)
                            .addComponent(facebook2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facebook5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n19))))
                .addContainerGap())
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 490));

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel As;
    private javax.swing.JLabel As1;
    private javax.swing.JLabel As2;
    private javax.swing.JLabel As3;
    private javax.swing.JLabel As4;
    private javax.swing.JLabel As5;
    private javax.swing.JLabel PaSe;
    private MyContainers.Background background1;
    private javax.swing.JLabel bienvenida2;
    private javax.swing.JLabel facebook1;
    private javax.swing.JLabel facebook2;
    private javax.swing.JLabel facebook3;
    private javax.swing.JLabel facebook4;
    private javax.swing.JLabel facebook5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel n10;
    private javax.swing.JLabel n11;
    private javax.swing.JLabel n12;
    private javax.swing.JLabel n13;
    private javax.swing.JLabel n14;
    private javax.swing.JLabel n15;
    private javax.swing.JLabel n16;
    private javax.swing.JLabel n17;
    private javax.swing.JLabel n18;
    private javax.swing.JLabel n19;
    private javax.swing.JLabel n6;
    private javax.swing.JLabel n7;
    private javax.swing.JLabel n8;
    private javax.swing.JLabel n9;
    private MyContainers.PanelRound panelRound1;
    private MyContainers.PanelRound panelRound2;
    private MyContainers.PanelRound panelRound3;
    private MyContainers.PanelRound panelRound4;
    private MyContainers.PanelRound panelRound5;
    private MyContainers.PanelRound panelRound6;
    private MyContainers.PanelRound panelRound7;
    // End of variables declaration//GEN-END:variables
}
